### ISSUE TITLE
Using Knife extension

### ISSUE THREAD

**Issue by xElkomy** [xnl-h4ck3r/knoxnl#23]
I think using the knife extension is better than using piper in the burp suite because there are a lot of problems and takes many machine resources during using the burp suite because that I prefer to use the knife extension instead of the piper.

Knfie Repo:
https://github.com/bit4woo/knife

**Comment by xElkomy** [comment]
![image](https://github.com/xnl-h4ck3r/knoxnl/assets/46958133/9d667463-0c68-44de-bf04-7c97337a3ea2)

```bash
knoxnl --input {RequestAsFile} --burp-piper -X BOTH
```

**Comment by blackcodersec** [comment]
hey @xElkomy 
did you try this knife?

**Comment by xnl-h4ck3r** [comment]
Hi @xElkomy. Apologies for the lack of response. I understand that knife may be better that piper, but realistically I don't think I will be using knife myself, and I don't think I'm going to get the time changing knoxnl to get this working with knife. If more people start using knife instead of piper and request this then I will reconsider in future. I hope you understand.
Thanks
Xnl
