### ISSUE TITLE
can add 2 API key

### ISSUE THREAD

**Issue by Elsfa7-110** [xnl-h4ck3r/knoxnl#25]
can add 2 API key in config file ?

if no

please make this idea

**Comment by xnl-h4ck3r** [comment]
Hi @Elsfa7-110 
I can see you have closed this. Just to say though. sing multiple API keys is not possible sorry. I won't be making that change because it is a wrapper around the KNOXSS API, and BruteLogic sets the API limits based for a reason. If every started using multiple keys then everyone would probably start getting performance issues. If you need to do more testing than one API key allows, then I would suggest messaging BruteLogic and discussing it with him. He provides great support.
Thanks for using knoxnl. Good luck finding some XSS!
