### ISSUE TITLE
Add new feature on `CheckPOC`

### ISSUE THREAD

**Issue by blackcodersec** [xnl-h4ck3r/knoxnl#26]
Check out the new features of knoxss. `CheckPOC` is the new function where we can send custom payloads. Please implement this function.

**Comment by xnl-h4ck3r** [comment]
Hey @blackcodersec , thanks for letting me know. I need to find out a bit more about it because I can't much documentation. I saw on Twitter that you pass `&checkpoc=1`. Is that all there is to it? So if the url contains a payload already and it pops, and you pass  `&checkpoc=1` you just get a success reponse?

**Comment by blackcodersec** [comment]
I am a little bit confused!
I recently tested that new method, but I saw the knoxss API shows the link is vulnerable and sometimes can't catch up. like, see some SS.

![{666DEBB1-10AC-456F-B2E5-8882ACF6936E}](https://github.com/user-attachments/assets/cc2d458d-0ac4-4ce2-b121-257e86e6b992)

but if you visit that link `http://testphp.vulnweb.com/listproducts.php?artist=<svg/onload=alert(1337)>`
you will get the pops.

![{FE4249DF-953C-4D17-8AF3-758A07367305}](https://github.com/user-attachments/assets/69356faf-a6f9-417e-b3b5-82127144b329)

also, I tried API method

![image](https://github.com/user-attachments/assets/ac26ba7a-aa5c-45c8-b0ac-9652e34ae227)

as brutelogic mention, and I saw on Twitter that you pass `&checkpoc=1`, I think I used right way. but not working. you can check now. If you want API key for testing purposes, please knock me on Discord (0xhunster_).

**Comment by blackcodersec** [comment]
> Hi @blackcodersec. Sorry for the delay, but I am looking at this now. I think your example didn't work because you used `alert(1337)`, but the KNOXSS FAQ say to use the number 1, e.g. `alert(1)` or the letter k, e.g. `alert(k)`

Thanks for the reply. When I made this issue, I did not check that FAQ page. Then I contacted brutelogic, and he told me to use `alert(1)` or the letter `alert(k)`, and I saw it was working. However, the problem is that I think the issue will happen when we want to use the payload list because sometimes we contain multiple different types of payloads. (I hope you understand my words)

**Comment by xnl-h4ck3r** [comment]
Hey. I'm not sure I fully understand what you mean by "the issue will happen when we want to use the payload list because sometimes we contain multiple different types of payloads". What payload list are you referring to?

**Comment by blackcodersec** [comment]
like I want to use this [payloadlist](https://github.com/payloadbox/xss-payload-list/blob/master/Intruder/xss-payload-list.txt) via for loop. check this screenshot. I hope you understand what I mean.

![image](https://github.com/user-attachments/assets/feedcdf9-6680-4de4-aea5-96d168f7f0b0)

**Comment by xnl-h4ck3r** [comment]
Hi @blackcodersec. I don't think that is really the purpose of the `checkPoc` function on the KNOXSS API. You don't need to try different payloads because KNOXSS does a lot of work to find a payload that works anyway. The use of `checkPoc` is to `validate a current PoC you already have`. So once you actually have a working PoC, you can validate this with KNOXSS, and then you could take your path and working PoC and then test it against other domains and sub-domnains of your target for example... so you can increase your chances of fininding an XSS on other targets based on PoC's you have already found.

**Comment by blackcodersec** [comment]
okk
