### ISSUE TITLE
output issue!

### ISSUE THREAD

**Issue by 0xhunster** [xnl-h4ck3r/knoxnl#5]
![image](https://github.com/xnl-h4ck3r/knoxnl/assets/46501627/563b3978-b2bc-4965-8f97-278570adfaad)

![image](https://github.com/xnl-h4ck3r/knoxnl/assets/46501627/e0229b00-966e-48bb-8790-36536a988370)

![image](https://github.com/xnl-h4ck3r/knoxnl/assets/46501627/17931b4c-197f-4337-a8d0-978cdd10e244)

`ERROR showOutput 1: 'NoneType' object has no attribute 'write'`

`-s` not working

**Comment by xnl-h4ck3r** [comment]
Hi @0xhunster. Thanks for using knoxnl and taking the time to log issues. Sorry you're having problems.
I will look into the `'NoneType' object has no attribute 'write'` but I think the `-s` is working ok. That argument is `-s, --success-only    Only show successful XSS payloads in the CLI output.` and your output shows a successful result. Sorry if the `-s` is confusing as I realise in hindsight you might think that meant `--silent` like a lot of other tools, which is why you thought that was an error?

**Comment by xnl-h4ck3r** [comment]
Hi @0xhunster. I have fixed the probelem that causes `ERROR showOutput 1: 'NoneType' object has no attribute 'write'` and prevents writing to the output file. If you can get v2.5 and confirm that you have no problems now, that'd be great.
Also, can you look at my last comment and confirm whether you stil think there is an issue with `-s`? Thanks

**Comment by 0xhunster** [comment]
Hi leet hacker 🤘,
Big fan sir 🤘
Thanks for your quick reply and for fixing the issue.
Now I understand `-s` how it works. I confirm that this function is okay, there is no problem.

And another problem is, if a line has a hash tag, that's still the script scanning the line. and API calls showing `Unknown`, I don't know why.

![image](https://github.com/xnl-h4ck3r/knoxnl/assets/46501627/d865a475-7519-476f-882e-50ac06e621c9)

Another thing, this is my request to you. Can you change the user-agent?

https://github.com/xnl-h4ck3r/knoxnl/blob/9566761f8ae37fe0b286c665eb17abf9222357b4/knoxnl/knoxnl.py#L207


🤘🤘 Overall Good boss! 🤘🤘

**Comment by xnl-h4ck3r** [comment]
Hi @0xhunster 
Thanks for the kind words.
I don't think it's really an error with knoxnl if the url starts with a `#` because that isn't a valid URL. I thin the user needs to ensure that only valid URLs are passed to knoxnl.
Also, I'm not going to allow the User-Agent to be changed. This is just the user agent sent to the KNOXSS API, so Brute Logic can know what traffic is from my tool. This isn't the User Agent sent to the target from the KNOXSS API if that is what you were worried about?
Thanks
